"""initial_medexa_schema

Revision ID: 231eff2db3d3
Revises: 
Create Date: 2026-08-31 18:51:31.592766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231eff2db3d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('facilities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.Enum('SUB_CENTRE', 'PHC', 'RURAL_HOSPITAL', 'DISTRICT_HOSPITAL', name='facilitytype'), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('village_or_ward', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('service_availability', sa.Enum('AVAILABLE', 'LIMITED', 'UNAVAILABLE', name='availabilitylevel'), nullable=False),
    sa.Column('diagnostic_availability', sa.Enum('AVAILABLE', 'LIMITED', 'UNAVAILABLE', name='availabilitylevel'), nullable=False),
    sa.Column('medicine_availability', sa.Enum('AVAILABLE', 'LIMITED', 'UNAVAILABLE', name='availabilitylevel'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_district'), 'facilities', ['district'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sex'), nullable=False),
    sa.Column('village_or_ward', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_village_or_ward'), 'patients', ['village_or_ward'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ASHA_WORKER', 'DOCTOR', 'DISTRICT_OFFICER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('care_episodes',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='careepisodestatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_episodes_patient_id'), 'care_episodes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_episodes_status'), 'care_episodes', ['status'], unique=False)
    op.create_table('continuity_risk_scores',
    sa.Column('care_episode_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='continuityrisklevel'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_episode_id'], ['care_episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continuity_risk_scores_care_episode_id'), 'continuity_risk_scores', ['care_episode_id'], unique=False)
    op.create_index(op.f('ix_continuity_risk_scores_level'), 'continuity_risk_scores', ['level'], unique=False)
    op.create_table('encounters',
    sa.Column('care_episode_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_episode_id'], ['care_episodes.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_care_episode_id'), 'encounters', ['care_episode_id'], unique=False)
    op.create_table('observations',
    sa.Column('care_episode_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_episode_id'], ['care_episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_care_episode_id'), 'observations', ['care_episode_id'], unique=False)
    op.create_table('referrals',
    sa.Column('care_episode_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('from_facility_id', sa.String(length=36), nullable=False),
    sa.Column('to_facility_id', sa.String(length=36), nullable=False),
    sa.Column('current_state', sa.Enum('DRAFT', 'SENT', 'RECEIVED', 'ACCEPTED', 'APPOINTMENT_QUEUED', 'CONSULTED', 'REFERRED_BACK', 'FOLLOW_UP_DUE', 'FOLLOW_UP_COMPLETED', 'CLOSED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'PATIENT_NO_SHOW', 'EMERGENCY_ESCALATED', name='referralstate'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('failure_reason', sa.Enum('FACILITY_FULL', 'SPECIALIST_UNAVAILABLE', 'PATIENT_COULD_NOT_TRAVEL', 'CONNECTIVITY_FAILURE', 'APPOINTMENT_UNAVAILABLE', 'PATIENT_NO_SHOW', 'COST_TRAVEL_BARRIER', 'REFERRAL_REJECTED', 'WRONG_FACILITY', 'OTHER', name='referralfailurereason'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_episode_id'], ['care_episodes.id'], ),
    sa.ForeignKeyConstraint(['from_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['to_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_care_episode_id'), 'referrals', ['care_episode_id'], unique=False)
    op.create_index(op.f('ix_referrals_current_state'), 'referrals', ['current_state'], unique=False)
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referrals_to_facility_id'), 'referrals', ['to_facility_id'], unique=False)
    op.create_table('triage_assessments',
    sa.Column('care_episode_id', sa.String(length=36), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('vitals', sa.JSON(), nullable=True),
    sa.Column('clinical_risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'EMERGENCY', name='clinicalrisklevel'), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_episode_id'], ['care_episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_assessments_care_episode_id'), 'triage_assessments', ['care_episode_id'], unique=False)
    op.create_index(op.f('ix_triage_assessments_clinical_risk_level'), 'triage_assessments', ['clinical_risk_level'], unique=False)
    op.create_table('back_referrals',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('medication', sa.JSON(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warning_signs', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=36), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_back_referrals_referral_id'), 'back_referrals', ['referral_id'], unique=True)
    op.create_table('follow_up_tasks',
    sa.Column('care_episode_id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'OVERDUE', name='followupstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['care_episode_id'], ['care_episodes.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_tasks_care_episode_id'), 'follow_up_tasks', ['care_episode_id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_referral_id'), 'follow_up_tasks', ['referral_id'], unique=False)
    op.create_index(op.f('ix_follow_up_tasks_status'), 'follow_up_tasks', ['status'], unique=False)
    op.create_table('referral_rescue_actions',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('action_taken', sa.Enum('NOTIFY_REFERRING_WORKER', 'ESCALATE_TO_SUPERVISOR', 'CREATE_PRIORITY_FOLLOW_UP', 'SUGGEST_ALTERNATE_FACILITY', name='rescueactiontype'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_rescue_actions_referral_id'), 'referral_rescue_actions', ['referral_id'], unique=False)
    op.create_table('referral_slas',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('acknowledgement_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appointment_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('back_referral_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_slas_referral_id'), 'referral_slas', ['referral_id'], unique=True)
    op.create_table('referral_state_transitions',
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.Enum('DRAFT', 'SENT', 'RECEIVED', 'ACCEPTED', 'APPOINTMENT_QUEUED', 'CONSULTED', 'REFERRED_BACK', 'FOLLOW_UP_DUE', 'FOLLOW_UP_COMPLETED', 'CLOSED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'PATIENT_NO_SHOW', 'EMERGENCY_ESCALATED', name='referralstate'), nullable=True),
    sa.Column('to_state', sa.Enum('DRAFT', 'SENT', 'RECEIVED', 'ACCEPTED', 'APPOINTMENT_QUEUED', 'CONSULTED', 'REFERRED_BACK', 'FOLLOW_UP_DUE', 'FOLLOW_UP_COMPLETED', 'CLOSED', 'REJECTED', 'CANCELLED', 'EXPIRED', 'PATIENT_NO_SHOW', 'EMERGENCY_ESCALATED', name='referralstate'), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_local_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_state_transitions_referral_id'), 'referral_state_transitions', ['referral_id'], unique=False)
    op.create_index(op.f('ix_referral_state_transitions_to_state'), 'referral_state_transitions', ['to_state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_state_transitions_to_state'), table_name='referral_state_transitions')
    op.drop_index(op.f('ix_referral_state_transitions_referral_id'), table_name='referral_state_transitions')
    op.drop_table('referral_state_transitions')
    op.drop_index(op.f('ix_referral_slas_referral_id'), table_name='referral_slas')
    op.drop_table('referral_slas')
    op.drop_index(op.f('ix_referral_rescue_actions_referral_id'), table_name='referral_rescue_actions')
    op.drop_table('referral_rescue_actions')
    op.drop_index(op.f('ix_follow_up_tasks_status'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_referral_id'), table_name='follow_up_tasks')
    op.drop_index(op.f('ix_follow_up_tasks_care_episode_id'), table_name='follow_up_tasks')
    op.drop_table('follow_up_tasks')
    op.drop_index(op.f('ix_back_referrals_referral_id'), table_name='back_referrals')
    op.drop_table('back_referrals')
    op.drop_index(op.f('ix_triage_assessments_clinical_risk_level'), table_name='triage_assessments')
    op.drop_index(op.f('ix_triage_assessments_care_episode_id'), table_name='triage_assessments')
    op.drop_table('triage_assessments')
    op.drop_index(op.f('ix_referrals_to_facility_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_current_state'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_care_episode_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_observations_care_episode_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_encounters_care_episode_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_continuity_risk_scores_level'), table_name='continuity_risk_scores')
    op.drop_index(op.f('ix_continuity_risk_scores_care_episode_id'), table_name='continuity_risk_scores')
    op.drop_table('continuity_risk_scores')
    op.drop_index(op.f('ix_care_episodes_status'), table_name='care_episodes')
    op.drop_index(op.f('ix_care_episodes_patient_id'), table_name='care_episodes')
    op.drop_table('care_episodes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_village_or_ward'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_district'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
